services:
  app:
    build:
      context: .
    #      platform: linux/arm64  #  ARM 대응
    container_name: voice-springboot
    depends_on:
      - db
    #      - flask
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      FLASK_URL: ${FLASK_URL}
    ports:
      - "8080:8080"
    restart: always
    networks:
      - backend

  db:
    image: mysql:8.0
    #    platform: linux/arm64  #  ARM 대응
    container_name: voice-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: voice-access-db
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    # ports:
    #   - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - backend

#  flask:
#    build:
#      context: ../voice_access_flask  # Flask Dockerfile이 있는 경로 (Spring과 병렬 위치)
#    container_name: flask
#    ports:
#      - "5001:5001"
#    networks:
#      - backend

networks:
  backend:

volumes:
  db_data: